name: build-test
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: setup spark
        uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.4.1'
          hadoop-version: '3'
          scala-version: '2.13'
          spark-url: 'https://archive.apache.org/dist/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3-scala2.13.tgz'
          xms: '1024M'
          xmx: '2048M'
          log-level: 'debug'
      - name: Test with pytest and chipsa
        run: |
          python -m pip install --upgrade pip
          pip install pytest chispa
          pytest