name: build-test
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  test: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Setup Spark
        run: |
          cd /tmp
          wget -q https://archive.apache.org/dist/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz
          tar xzf spark-3.5.0-bin-hadoop3.tgz -C /home/runner
          rm spark-3.5.0-bin-hadoop3.tgz
          echo SPARK_HOME=/home/runner/spark-3.5.0-bin-hadoop3.tgz >> $GITHUB_ENV
      - name: Test with pytest and chipsa
        run: |
          python -m pip install --upgrade pip
          pip install pytest chispa
          pytest